name: metamap_plugin_flutter
description: Flutter plugin for Mati SDK.

version: 4.0.3
homepage: 'https://github.com/GetMati/mati-flutter-plugin'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.getmati.metamap_plugin_flutter
        pluginClass: MatiPluginFlutterPlugin
      ios:
        pluginClass: MatiPluginFlutterPlugin
